---
- name: Crear directorios y mover archivos a la ruta de la pagina
  hosts: webservers
  become: yes
  vars_files:
    vars.yml

  tasks:
    - name: Crear carpeta raiz
      file:
        path: "/var/www/html/{{ http_host }}/web"
        state: directory
        mode: '0755'

    - name: Copiar archivos hacia la carpeta raiz
      copy:
        src: "{{ item }}"
        dest: "/var/www/html/{{ http_host }}/web/"
        mode: 0775
      with_fileglob:
        - "~/ansible/files/pagina/web/*"

    - name: Copiar archivo conf
      template:
        src: "~/ansible/files/0AAgundis-web.conf"
        dest: "/etc/apache2/sites-available/0AAgundis-web.conf"

    - name: Crear carpeta raiz
      file:
        path: "/var/www/html/{{ http_host }}/app"
        state: directory
        mode: '0755'

    - name: Copiar archivos hacia la carpeta raiz
      copy:
        src: "{{ item }}"
        dest: "/var/www/html/{{ http_host }}/app/"
        mode: 0755
      with_fileglob:
        - "~/ansible/files/pagina/*"

    - name: Copiar archivo conf
      template:
        src: "~/ansible/files/AAgundis-web-app.conf"
        dest: "/etc/apache2/sites-available/AAgundis-web-app.conf"


