---
- name: habilitar sitios web
  become: yes
  hosts: webservers
  vars_files:
    vars.yml

  tasks:
    - name: habilitar web
      command: a2ensite 0AAgundis-web.conf

    - name: habilitar app
      command: a2ensite AAgundis-web-app.conf

    - name: habilitar puerto "{{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

    - name: dehabilitar sitio default
      command: a2dissite 000-default.conf

    - name: recargar apache
      service:
        name: apache2
        state: reloaded

    - name: reiniciar apache
      service:
        name: apache2
        state: started
